project_id = "pdlmsicltphrvzeczzby"

[functions.gmail-scan]
verify_jwt = false

[functions.gmail-unsubscribe]
verify_jwt = false

[functions.analyze-spam]
verify_jwt = false

[functions.gmail-auth-url]
verify_jwt = false

[functions.gmail-oauth-callback]
verify_jwt = false

[functions.gmail-token-exchange]
verify_jwt = false
